#!/usr/bin/env python                                                                    
# -*- coding: UTF-8 -*-                                                                  
#post-receive               

from operator import contains
import os
import re
import sys

def get_text_from_file(path):
    with open(path, "r", encoding="utf-8") as file:
        text = file.read()
    return text

commit_msg_path = sys.argv[1]
commit_msg = get_text_from_file(commit_msg_path).strip().lower()

help_dir = os.path.join(os.path.dirname(__file__), "Help")
help_msg = get_text_from_file(os.path.join(help_dir, "commit-msg.txt"))
available_commit = set(get_text_from_file(os.path.join(help_dir, "available-commit-msg.txt")).split('|'))

type = re.split("[\(:]", commit_msg)[0]
    
if available_commit.__contains__(type) and re.match(type + "(\(.{3,15}\))?: .{10,}", commit_msg):
    print("Success!")
else:
    print(help_msg)
    raise SystemExit(1)


#print(help_msg)
